// <auto-generated />
using System;
using JobsLibrary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace JobsLibrary.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200615125640_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("JobsLibrary.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<string>("Company")
                        .HasColumnName("company")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Date")
                        .HasColumnName("date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasColumnType("text");

                    b.Property<string>("Href")
                        .HasColumnName("href")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnName("location")
                        .HasColumnType("text");

                    b.Property<string>("OriginalWebsite")
                        .HasColumnName("original_website")
                        .HasColumnType("text");

                    b.Property<string>("Salary")
                        .HasColumnName("salary")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnName("title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("job");

                    b.HasData(
                        new
                        {
                            Id = new Guid("396741ca-d70d-4903-b40e-6a337ee8691f"),
                            Company = "Test company",
                            Date = new DateTime(2020, 6, 15, 8, 56, 40, 578, DateTimeKind.Local).AddTicks(3946),
                            Description = "Test description",
                            Href = "www.google.com",
                            Location = "Australia",
                            OriginalWebsite = "Test",
                            Salary = "a lot :)",
                            Title = "Test title"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
